export const INPUT_NUMBER = "INPUT_NUMBER";
export const CLEAR_DISPLAY = "CLEAR_DISPLAY";
export const SAFE_ACCESS_SUCCESS = "SAFE_ACCESS_SUCCESS";
export const SAFE_ACCESS_FAILED = "SAFE_ACCESS_FAILED";
export const SAFE_LOCK_SUCCESS = "SAFE_LOCK_SUCCESS";
export const SAFE_LOCK_FAILED = "SAFE_LOCK_FAILED";
